# Generated by Django 4.2 on 2026-05-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollplaza_contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='tollplaza_contact',
            name='tollplaza',
        ),
        migrations.DeleteModel(
            name='Parking_contact',
        ),
        migrations.DeleteModel(
            name='Tollplaza_contact',
        ),
    ]
