# Generated by Django 4.2 on 2026-04-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollplaza',
            name='Contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contractor'),
        ),
    ]
