# Generated by Django 4.2 on 2026-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_tollplaza_contact_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
