# Generated by Django 4.2 on 2026-04-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_tollplaza_contractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tollplaza',
            old_name='Contractor',
            new_name='contractor',
        ),
    ]
