# Generated by Django 4.2 on 2026-05-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.channel')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.parking')),
            ],
            options={
                'db_table': 'parking_channel',
            },
        ),
    ]
