# Generated by Django 4.2 on 2026-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_contractor_tollplaza_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollplaza',
            name='contractor',
        ),
        migrations.DeleteModel(
            name='Tollplaza_contractor',
        ),
        migrations.AddField(
            model_name='tollplaza',
            name='contractor',
            field=models.ManyToManyField(blank=True, to='contacts.contractor'),
        ),
    ]
