# Generated by Django 4.2 on 2026-05-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_parking_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contractor'),
        ),
        migrations.AlterModelTable(
            name='contractor',
            table='contractor',
        ),
    ]
