# Generated by Django 4.2 on 2026-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_tollplaza_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('tollplaza', 'TollPlaza'), ('parking', 'Parking'), ('office', 'Office')], default='parking', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
