# Generated by Django 4.2 on 2026-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_contact_type_alter_contact_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('tollplaza', 'TollPlaza'), ('parking', 'Parking'), ('office', 'Office')], default='tollplaza', max_length=20),
        ),
    ]
