# Generated by Django 4.2 on 2026-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_firstname_alter_contact_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ'),
        ),
    ]
