# Generated by Django 4.2 on 2026-05-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contact_firstname_alter_contact_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.type')),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='Offices',
            field=models.ManyToManyField(blank=True, to='contacts.office'),
        ),
    ]
