# Generated by Django 4.2 on 2026-05-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_office_contact_offices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['firstname', 'lastname'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Offices',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('tollplaza', 'TollPlaza'), ('parking', 'Parking'), ('office', 'Office')], default='tollplaza', max_length=20, verbose_name='Loại liên hệ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='parkings',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tollplazas',
        ),
        migrations.AddField(
            model_name='contact',
            name='parkings',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='contacts.Parking_contact', to='contacts.parking'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tollplazas',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='contacts.Tollplaza_contact', to='contacts.tollplaza'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.titles', verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.office'),
        ),
    ]
